### ISSUE TITLE
Metaissue of things to do 

### ISSUE THREAD

**Issue by tracykteal** [openjournals/jose#7]
This is a meta-issue of things to do for JOSE from conversation with @arfon @katyhuff @labarba @kyleniemeyer. These should likely be broken out into separate issues. 

- [ ]  scope of work for JOSE features different from JOSS
    - [ ] be able to search based on keywords
- [x] reviewer checklist for education articles
- [x] reviewer checklist for lessons
- [ ] editor guidelines for each
- [x] description of the types of content the journal will accept
- [ ] metadata tags
- [ ] keywords for submissions, and ability to search based on these
- [x] tag existing issues in the joss or whedon repos which would be high priority for jose
- [x] template email to potential reviewers describing the journal and asking people to review
